application: aecs1980qg

version: v1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /static
  static_dir: static

- url: /tasks/.*
  script: crontasks.app
  login: admin
  
- url: /.*
  script: main.app